### ISSUE TITLE
Provide Debian packages

### ISSUE THREAD

**Issue by tkem** [tkem/mopidy-internetarchive#57]
Although this is kind of a "niche" extension, and @jodal seems busy with more urgent Mopidy v1.2 tasks, it would be nice if mopidy-internetarchive was also available from apt.mopidy.com. If only to provide more content for the "Installation" section on RTD ;-)

**Comment by jodal** [comment]
I've put it on my packaging todo list. :-)

**Comment by tkem** [comment]
Thanks ;-)

**Comment by jodal** [comment]
I've now made a Debian package of mopidy-internetarchive.

It's available in the jessie dist at apt.mopidy.com. The wheezy build failed due to a too old pytest, and I don't want to disable the package's test suite just to get support for oldstable. The package has been uploaded to Debian unstable and will probably sync to Ubuntu in time to be included in Ubuntu 16.04 LTS.

The package source can be browsed at https://anonscm.debian.org/cgit/pkg-mopidy/mopidy-internetarchive.git/.

**Comment by tkem** [comment]
Yay!!! Thanks a lot. If you ever feel like needing a helping hand/backup with all that packaging, just let me know.

**Comment by jodal** [comment]
No problem so far, but I've started moving all packages to the pkg-mopidy team at Alioth to make it easier to let others help in the future :-)
